name: Test jac-scale

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-all:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v5
        with:
          submodules: true

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install Jaseci scale package
        run: |
          python -m pip install --upgrade pip
          pip install -e jac
          pip install -e jac-scale
          pip install pytest
          pip install pytest-asyncio
          pip install -e jac-client

      - name: Run Backend tests
        run: |
          pytest -v jac-scale/jac_scale/tests/test_serve.py

      - name: Run jac-client examples
        run: |
          pytest -v jac-scale/jac_scale/tests/test_examples.py

      - name: Run SSO tests
        run: |
          pytest -v jac-scale/jac_scale/tests/test_sso.py

      - name: Check for Kubernetes changes
        id: k8s-changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            k8s:
              - 'jac-scale/jac_scale/kubernetes/**'

      - name: Install Kind (Kubernetes in Docker)
        if: steps.k8s-changes.outputs.k8s == 'true'
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.25.0/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind
          kind version

      - name: Create Kubernetes cluster with Kind
        if: steps.k8s-changes.outputs.k8s == 'true'
        run: |
          kind create cluster --name jaseci-test --wait 60s
          kubectl cluster-info
          kubectl get nodes

      - name: Run K8 tests
        if: steps.k8s-changes.outputs.k8s == 'true'
        run: |
          pytest -v jac-scale/jac_scale/tests/test_deploy_k8.py

      - name: Delete Kind cluster
        if: always() && steps.k8s-changes.outputs.k8s == 'true'
        run: kind delete cluster --name jaseci-test
